version: "3.9"
services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tododb  
    ports: 
      - "5432:5432"
